// class Autogenerated {
//   bool? status;
//   String? msg;
//   List<Result>? result;
//
//   Autogenerated({this.status, this.msg, this.result});
//
//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     status = json['status'];
//     msg = json['msg'];
//     if (json['result'] != null) {
//       result = <Result>[];
//       json['result'].forEach((v) {
//         result!.add(new Result.fromJson(v));
//       });
//     }
//   }
//
//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['status'] = this.status;
//     data['msg'] = this.msg;
//     if (this.result != null) {
//       data['result'] = this.result!.map((v) => v.toJson()).toList();
//     }
//     return data;
//   }
// }

class AddressRepo {
  bool? status;
  String? msg;
  dynamic result;

  AddressRepo({this.result, this.status, this.msg});
  factory AddressRepo.fromJson(Map<dynamic, dynamic> json) {
    try {
      return AddressRepo(
          result: json['result'],
          status: json['status'],
          msg: json['msg']
      );
    } catch (error) {
      return AddressRepo(
        status: false,
        result: null,
        msg:"",
      );
    }
  }
}


class AddressModel {
  String? id;
  String? streetAddress;
  String? city;
  String? state;
  String? pincode;

  AddressModel({this.id, this.streetAddress, this.city, this.state, this.pincode});

  AddressModel.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    streetAddress = json['street_address'];
    city = json['city'];
    state = json['state'];
    pincode = json['pincode'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['street_address'] = this.streetAddress;
    data['city'] = this.city;
    data['state'] = this.state;
    data['pincode'] = this.pincode;
    return data;
  }
}

class AddAddressRepo {
  bool? status;
  String? msg;

  AddAddressRepo({ this.status, this.msg});
  factory AddAddressRepo.fromJson(Map<dynamic, dynamic> json) {
    try {
      return AddAddressRepo(
          status: json['status'],
          msg: json['msg']
      );
    } catch (error) {
      return AddAddressRepo(
        status: false,
        msg:"",
      );
    }
  }
}